package com.geekinasuit.polyglot.brackets.service.dagger

import com.geekinasuit.polyglot.brackets.service.BalanceServiceEndpointAdapter
import dagger.Module
import dagger.Provides
import dagger.multibindings.IntoSet
import io.grpc.BindableService

/**
 * Contributes gRPC service adapters to the Set<BindableService> multibinding. Hand-written;
 * intended to be generated by dagger-grpc module_generator.
 */
@Module
object GrpcHandlersModule {
  @Provides
  @IntoSet
  fun balanceHandler(supplier: GrpcCallScopeGraph.Supplier): BindableService =
      BalanceServiceEndpointAdapter {
        supplier.callScope().balance()
      }
}
