package com.geekinasuit.polyglot.brackets.service.dagger

import com.geekinasuit.daggergrpc.api.GrpcCallScope
import com.geekinasuit.polyglot.brackets.service.BalanceServiceEndpoint
import dagger.Subcomponent

/**
 * Per-call subcomponent. Hand-written; intended to be generated by dagger-grpc module_generator.
 */
@GrpcCallScope
@Subcomponent(modules = [GrpcCallScopeGraphModule::class])
interface GrpcCallScopeGraph {
  fun balance(): BalanceServiceEndpoint

  interface Supplier {
    fun callScope(): GrpcCallScopeGraph
  }
}
