// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v3.19.1
// source: brackets_service.proto

/* eslint-disable */
import { type handleUnaryCall, Metadata, type UntypedServiceImplementation } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import _m0 from "protobufjs/minimal";
import { Observable } from "rxjs";

export const protobufPackage = "brackets_service";

export interface BalanceRequest {
  statement: string;
}

export interface BalanceResponse {
  succeeded: boolean;
  error: string;
  isBalanced: boolean;
}

export const BRACKETS_SERVICE_PACKAGE_NAME = "brackets_service";

function createBaseBalanceRequest(): BalanceRequest {
  return { statement: "" };
}

export const BalanceRequest = {
  encode(message: BalanceRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.statement !== "") {
      writer.uint32(10).string(message.statement);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): BalanceRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBalanceRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.statement = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },
};

function createBaseBalanceResponse(): BalanceResponse {
  return { succeeded: false, error: "", isBalanced: false };
}

export const BalanceResponse = {
  encode(message: BalanceResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.succeeded !== false) {
      writer.uint32(8).bool(message.succeeded);
    }
    if (message.error !== "") {
      writer.uint32(18).string(message.error);
    }
    if (message.isBalanced !== false) {
      writer.uint32(24).bool(message.isBalanced);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): BalanceResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBalanceResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.succeeded = reader.bool();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.error = reader.string();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.isBalanced = reader.bool();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },
};

export interface BalanceBracketsClient {
  balance(request: BalanceRequest, metadata?: Metadata): Observable<BalanceResponse>;
}

export interface BalanceBracketsController {
  balance(
    request: BalanceRequest,
    metadata?: Metadata,
  ): Promise<BalanceResponse> | Observable<BalanceResponse> | BalanceResponse;
}

export function BalanceBracketsControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["balance"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("BalanceBrackets", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("BalanceBrackets", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const BALANCE_BRACKETS_SERVICE_NAME = "BalanceBrackets";

export type BalanceBracketsService = typeof BalanceBracketsService;
export const BalanceBracketsService = {
  balance: {
    path: "/brackets_service.BalanceBrackets/Balance",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: BalanceRequest) => Buffer.from(BalanceRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => BalanceRequest.decode(value),
    responseSerialize: (value: BalanceResponse) => Buffer.from(BalanceResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer) => BalanceResponse.decode(value),
  },
} as const;

export interface BalanceBracketsServer extends UntypedServiceImplementation {
  balance: handleUnaryCall<BalanceRequest, BalanceResponse>;
}
